name: jlabtutorial
channels:
  - damianavila82
  - mcs07
  - mordred-descriptor
  - anaconda
  - conda-forge
  - rmg
  - defaults
dependencies:
  - python
  - numpy
  - pip
  - matplotlib
  - ipython=7.10.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jpeg
  - json5
  - jsonschema
  - matplotlib
  - mkl
  - mordred
  - numpy
  - pandas
  - rdkit=2019.09.2
  - py3dmol
  - pip:
    - deap==1.3.0
    - joblib==0.14.1
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - scikit-learn==0.22
    - scikit-multilearn==0.2.0
    - scipy==1.3.3
    - stopit==1.1.2
    - tpot==0.11.0
    - update-checker==0.16
    - xgboost==0.90
    - ipymol
